### ISSUE TITLE
Please produce a new versioned release of schemer-rusqlite

### ISSUE THREAD

**Issue by nuttycom** [aschampion/schemer#16]
I would like to make a new crate release that depends upon the latest version of schemer, but cargo doesn't allow publishing releases with patch dependencies; if it's not to great of a hassle could you please make a new release of the schemer-rusqlite crate?

Thanks, Kris

**Comment by aschampion** [comment]
This should be addressed by 92ce8d92059108772068e68adec792c21f56e38b once GH actions handles it.

**Comment by nuttycom** [comment]
Thank you!
